_wandb:
    value:
        cli_version: 0.18.6
        m:
            - "1": epoch/val_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/epoch
              "6":
                - 3
              "7": []
            - "1": epoch/loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/val_accuracy
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/accuracy
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/learning_rate
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.10.14
        t:
            "1":
                - 2
                - 3
                - 5
                - 12
                - 49
                - 51
                - 53
                - 55
                - 105
            "2":
                - 2
                - 3
                - 5
                - 12
                - 49
                - 51
                - 53
                - 55
                - 105
            "3":
                - 2
                - 7
                - 23
                - 38
                - 55
            "4": 3.10.14
            "5": 0.18.6
            "8":
                - 1
                - 2
                - 5
            "12": 0.18.6
            "13": linux-x86_64
